// Copyright (c) 2023 Mattia Cabrini
// SPDX-License-Identifier: MIT

package utility

import "database/sql"

/*
To commit or rollback a transaction:

  - If err is nil, tx is committed;
  - If err is not nil, tx is rolled back.

Parameters:

  - tx *sql.Tx;
  - err error.

Returns:

  - err error: an error generated by tx.Commit or by tx.Rollback.
*/
func CommitTx(tx *sql.Tx, err error) (_ error) {
	if err == nil {
		err = tx.Commit()
	} else {
		err = tx.Rollback()
	}

	return AppendError(err)
}
